#Constants
#Template files
LAYER_TEMPLATE_HEADER = '/include/layers'
LAYER_TEMPLATE_SOURCE = '/src/layers'

ACTIVATION_HEADER = '/include/activation_func.h'
ACTIVATION_SOURCE = '/src/activation_func.cpp'

PARAMETERS_HEADER = '/include/parameters.h'

NEURAL_NETWORK_HEADER = '/include/nn4mc.h'
NEURAL_NETWORK_SOURCE = '/src/nn4mc.cpp'

#Delimiters
#Start and end of template
START_DELIMITER = '<%BEGIN_DEFINITION_TEMPLATE>'
END_DELIMITER = '<%END_DEFINITION_TEMPLATE>'

#Datatypes
WEIGHT_DATATYPE_DELIMITER = '<%WEIGHT_DATATYPE_DELIMITER>'
INDEX_DATATYPE_DELIMITER = '<%INDEX_DATATYPE_DELIMITER>'
LAYER_DATATYPE_DELIMITER = '<%LAYER_DATATYPE_DELIMITER>'
ACTIVATION_DATATYPE_DELIMITER = '<%ACTIVATION_DATATYPE_DELIMITER>'

# #Template function call
# START_CALL_DELIMITER = '<%START_CALL_TEMPLATE>'
# END_CALL_DELIMITER = '<%END_CALL_TEMPLATE>'
#
# #Template initialize call
# START_INIT_DELIMITER = '<%START_INITIALIZE_TEMPLATE'
# END_INIT_DELIMITER = '<%END_INITIALIZE_TEMPLATE>'

#Locations for function calls and definitions
NN_INIT_DELIMITER = '<%BUILD_FUNCTION>'
NN_FWD_DELIMITER = '<%FWD_FUNCTION>'
NN_INCLUDE_DELIMITER = '<%INCLUDE>'
NN_STRUCT_DELIMITER = '<%STRUCTS>'

W_WEIGHT_DELIMITER = '<%WEIGHT>'

ACTIVATIONS_DELIMITER = '<%ACTIVATIONS>'

ACTIVATION_FUNCTION_DELIMITER = '<%ACTIVATION_FUNCTION>'

# #Weight stuff and init stuff
# WEIGHT_NAME = '<%WEIGHT_NAME>'
# BIAS_NAME = '<%BIAS_NAME>'
# WEIGHT_INDEX = '<%WEIGHT_INDEX>'
# WEIGHT_DATA = '<%WEIGHT_DATA>'
# LAYER_NAME = '<%LAYER_NAME>'
# KERNEL_SHAPE_0 = '<%KERNEL_SHAPE_0>'
# KERNEL_SHAPE_1 = '<%KERNEL_SHAPE_1>'
# FILTERS = '<%FILTERS>'
# STRIDE_SHAPE_0 = '<%STRIDE_SHAPE_0>'
# STRIDE_SHAPE_1 = '<%STRIDE_SHAPE_1>'
# INPUT_SHAPE_0 = '<%INPUT_SHAPE_0>'
# INPUT_SHAPE_1 = '<%INPUT_SHAPE_1>'
# INPUT_SHAPE_2 = '<%INPUT_SHAPE_2>'
# ACTIVATION = '<%ACTIVATION>'
