# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gru', [dirname(__file__)])
        except ImportError:
            import _gru
            return _gru
        if fp is not None:
            try:
                _mod = imp.load_module('_gru', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gru = swig_import_helper()
    del swig_import_helper
else:
    import _gru
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def build_layer_gru(W, U, b, recurrent_activation, activation, input_shape_0, input_shape_1, output_units):
    return _gru.build_layer_gru(W, U, b, recurrent_activation, activation, input_shape_0, input_shape_1, output_units)
build_layer_gru = _gru.build_layer_gru

def fwd_gru(L, input):
    return _gru.fwd_gru(L, input)
fwd_gru = _gru.fwd_gru
class GRU(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GRU, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GRU, name)
    __repr__ = _swig_repr
    __swig_setmethods__["weights"] = _gru.GRU_weights_set
    __swig_getmethods__["weights"] = _gru.GRU_weights_get
    if _newclass:
        weights = _swig_property(_gru.GRU_weights_get, _gru.GRU_weights_set)
    __swig_setmethods__["big_u"] = _gru.GRU_big_u_set
    __swig_getmethods__["big_u"] = _gru.GRU_big_u_get
    if _newclass:
        big_u = _swig_property(_gru.GRU_big_u_get, _gru.GRU_big_u_set)
    __swig_setmethods__["biases"] = _gru.GRU_biases_set
    __swig_getmethods__["biases"] = _gru.GRU_biases_get
    if _newclass:
        biases = _swig_property(_gru.GRU_biases_get, _gru.GRU_biases_set)
    __swig_setmethods__["weight_shape"] = _gru.GRU_weight_shape_set
    __swig_getmethods__["weight_shape"] = _gru.GRU_weight_shape_get
    if _newclass:
        weight_shape = _swig_property(_gru.GRU_weight_shape_get, _gru.GRU_weight_shape_set)
    __swig_setmethods__["big_u_shape"] = _gru.GRU_big_u_shape_set
    __swig_getmethods__["big_u_shape"] = _gru.GRU_big_u_shape_get
    if _newclass:
        big_u_shape = _swig_property(_gru.GRU_big_u_shape_get, _gru.GRU_big_u_shape_set)
    __swig_setmethods__["biases_shape"] = _gru.GRU_biases_shape_set
    __swig_getmethods__["biases_shape"] = _gru.GRU_biases_shape_get
    if _newclass:
        biases_shape = _swig_property(_gru.GRU_biases_shape_get, _gru.GRU_biases_shape_set)
    __swig_setmethods__["recurrent_activation"] = _gru.GRU_recurrent_activation_set
    __swig_getmethods__["recurrent_activation"] = _gru.GRU_recurrent_activation_get
    if _newclass:
        recurrent_activation = _swig_property(_gru.GRU_recurrent_activation_get, _gru.GRU_recurrent_activation_set)
    __swig_setmethods__["activation"] = _gru.GRU_activation_set
    __swig_getmethods__["activation"] = _gru.GRU_activation_get
    if _newclass:
        activation = _swig_property(_gru.GRU_activation_get, _gru.GRU_activation_set)
    __swig_setmethods__["input_shape"] = _gru.GRU_input_shape_set
    __swig_getmethods__["input_shape"] = _gru.GRU_input_shape_get
    if _newclass:
        input_shape = _swig_property(_gru.GRU_input_shape_get, _gru.GRU_input_shape_set)
    __swig_setmethods__["output_shape"] = _gru.GRU_output_shape_set
    __swig_getmethods__["output_shape"] = _gru.GRU_output_shape_get
    if _newclass:
        output_shape = _swig_property(_gru.GRU_output_shape_get, _gru.GRU_output_shape_set)
    __swig_setmethods__["h_tm1"] = _gru.GRU_h_tm1_set
    __swig_getmethods__["h_tm1"] = _gru.GRU_h_tm1_get
    if _newclass:
        h_tm1 = _swig_property(_gru.GRU_h_tm1_get, _gru.GRU_h_tm1_set)

    def __init__(self):
        this = _gru.new_GRU()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _gru.delete_GRU
    __del__ = lambda self: None
GRU_swigregister = _gru.GRU_swigregister
GRU_swigregister(GRU)


def activate(arg1, arg2, arg3):
    return _gru.activate(arg1, arg2, arg3)
activate = _gru.activate

def sigmoid(arg1, arg2):
    return _gru.sigmoid(arg1, arg2)
sigmoid = _gru.sigmoid

def softplus(arg1, arg2):
    return _gru.softplus(arg1, arg2)
softplus = _gru.softplus

def softsign(arg1, arg2):
    return _gru.softsign(arg1, arg2)
softsign = _gru.softsign

def hard_sigmoid(arg1, arg2):
    return _gru.hard_sigmoid(arg1, arg2)
hard_sigmoid = _gru.hard_sigmoid

def exp_activation(arg1, arg2):
    return _gru.exp_activation(arg1, arg2)
exp_activation = _gru.exp_activation

def exponential(arg1):
    return _gru.exponential(arg1)
exponential = _gru.exponential

def relu(arg1, arg2):
    return _gru.relu(arg1, arg2)
relu = _gru.relu

def elu(arg1, arg2, arg3):
    return _gru.elu(arg1, arg2, arg3)
elu = _gru.elu

def selu(arg1, arg2):
    return _gru.selu(arg1, arg2)
selu = _gru.selu

def hyper_tan(arg1, arg2):
    return _gru.hyper_tan(arg1, arg2)
hyper_tan = _gru.hyper_tan

def softmax(arg1, arg2):
    return _gru.softmax(arg1, arg2)
softmax = _gru.softmax
class input(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, input, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, input, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _gru.new_input(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _gru.delete_input
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _gru.input___getitem__(self, index)

    def __setitem__(self, index, value):
        return _gru.input___setitem__(self, index, value)

    def cast(self):
        return _gru.input_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _gru.input_frompointer
    if _newclass:
        frompointer = staticmethod(_gru.input_frompointer)
input_swigregister = _gru.input_swigregister
input_swigregister(input)
cvar = _gru.cvar
conv1d_1_W = cvar.conv1d_1_W
conv1d_1_b = cvar.conv1d_1_b
conv1d_2_W = cvar.conv1d_2_W
conv1d_2_b = cvar.conv1d_2_b
dense_1_W = cvar.dense_1_W
dense_1_b = cvar.dense_1_b
dense_2_W = cvar.dense_2_W
dense_2_b = cvar.dense_2_b
dense_3_W = cvar.dense_3_W
dense_3_b = cvar.dense_3_b
dense_4_W = cvar.dense_4_W
dense_4_b = cvar.dense_4_b
dense_5_W = cvar.dense_5_W
dense_5_b = cvar.dense_5_b
dense_6_W = cvar.dense_6_W
dense_6_b = cvar.dense_6_b
dense_7_W = cvar.dense_7_W
dense_7_b = cvar.dense_7_b
dense_8_W = cvar.dense_8_W
dense_8_b = cvar.dense_8_b

def input_frompointer(t):
    return _gru.input_frompointer(t)
input_frompointer = _gru.input_frompointer

# This file is compatible with both classic and new-style classes.


