# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dense
else:
    import _dense

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def build_layer_dense(W, b, input_size, output_size, activation):
    return _dense.build_layer_dense(W, b, input_size, output_size, activation)

def fwd_dense(L, input):
    return _dense.fwd_dense(L, input)
class Dense(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    weights = property(_dense.Dense_weights_get, _dense.Dense_weights_set)
    biases = property(_dense.Dense_biases_get, _dense.Dense_biases_set)
    activation = property(_dense.Dense_activation_get, _dense.Dense_activation_set)
    weight_shape = property(_dense.Dense_weight_shape_get, _dense.Dense_weight_shape_set)
    input_shape = property(_dense.Dense_input_shape_get, _dense.Dense_input_shape_set)
    output_shape = property(_dense.Dense_output_shape_get, _dense.Dense_output_shape_set)

    def __init__(self):
        _dense.Dense_swiginit(self, _dense.new_Dense())
    __swig_destroy__ = _dense.delete_Dense

# Register Dense in _dense:
_dense.Dense_swigregister(Dense)

class input(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _dense.input_swiginit(self, _dense.new_input(nelements))
    __swig_destroy__ = _dense.delete_input

    def __getitem__(self, index):
        return _dense.input___getitem__(self, index)

    def __setitem__(self, index, value):
        return _dense.input___setitem__(self, index, value)

    def cast(self):
        return _dense.input_cast(self)

    @staticmethod
    def frompointer(t):
        return _dense.input_frompointer(t)

# Register input in _dense:
_dense.input_swigregister(input)
cvar = _dense.cvar
conv1d_1_W = cvar.conv1d_1_W
conv1d_1_b = cvar.conv1d_1_b
conv1d_2_W = cvar.conv1d_2_W
conv1d_2_b = cvar.conv1d_2_b
dense_1_W = cvar.dense_1_W
dense_1_b = cvar.dense_1_b
dense_2_W = cvar.dense_2_W
dense_2_b = cvar.dense_2_b
dense_3_W = cvar.dense_3_W
dense_3_b = cvar.dense_3_b
dense_4_W = cvar.dense_4_W
dense_4_b = cvar.dense_4_b
dense_5_W = cvar.dense_5_W
dense_5_b = cvar.dense_5_b
dense_6_W = cvar.dense_6_W
dense_6_b = cvar.dense_6_b
dense_7_W = cvar.dense_7_W
dense_7_b = cvar.dense_7_b
dense_8_W = cvar.dense_8_W
dense_8_b = cvar.dense_8_b

def input_frompointer(t):
    return _dense.input_frompointer(t)


def activate(input, output_shape, type):
    return _dense.activate(input, output_shape, type)

def sigmoid(input, m):
    return _dense.sigmoid(input, m)

def exp_activation(input, m):
    return _dense.exp_activation(input, m)

def softplus(input, m):
    return _dense.softplus(input, m)

def softsign(input, m):
    return _dense.softsign(input, m)

def hard_sigmoid(input, m):
    return _dense.hard_sigmoid(input, m)

def exponential(input):
    return _dense.exponential(input)

def relu(input, m):
    return _dense.relu(input, m)

def hyper_tan(input, m):
    return _dense.hyper_tan(input, m)

def softmax(input, m):
    return _dense.softmax(input, m)


