# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _conv2d
else:
    import _conv2d

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def build_layer_conv2d(W, b, kernel_shape_0, kernel_shape_1, filters, strides_0, strides_1, input_shape_0, input_shape_1, input_shape_2, activation, padding, data_format, dilation_rate_0, dilation_rate_1):
    return _conv2d.build_layer_conv2d(W, b, kernel_shape_0, kernel_shape_1, filters, strides_0, strides_1, input_shape_0, input_shape_1, input_shape_2, activation, padding, data_format, dilation_rate_0, dilation_rate_1)

def padding_2d(L, input, shape_0_change, shape_1_change):
    return _conv2d.padding_2d(L, input, shape_0_change, shape_1_change)

def fwd_conv2d(L, input):
    return _conv2d.fwd_conv2d(L, input)
class Conv2D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    weights = property(_conv2d.Conv2D_weights_get, _conv2d.Conv2D_weights_set)
    bias = property(_conv2d.Conv2D_bias_get, _conv2d.Conv2D_bias_set)
    weight_shape = property(_conv2d.Conv2D_weight_shape_get, _conv2d.Conv2D_weight_shape_set)
    strides = property(_conv2d.Conv2D_strides_get, _conv2d.Conv2D_strides_set)
    filters = property(_conv2d.Conv2D_filters_get, _conv2d.Conv2D_filters_set)
    dilation_rate = property(_conv2d.Conv2D_dilation_rate_get, _conv2d.Conv2D_dilation_rate_set)
    activation = property(_conv2d.Conv2D_activation_get, _conv2d.Conv2D_activation_set)
    padding = property(_conv2d.Conv2D_padding_get, _conv2d.Conv2D_padding_set)
    data_format = property(_conv2d.Conv2D_data_format_get, _conv2d.Conv2D_data_format_set)
    kernel_shape = property(_conv2d.Conv2D_kernel_shape_get, _conv2d.Conv2D_kernel_shape_set)
    input_shape = property(_conv2d.Conv2D_input_shape_get, _conv2d.Conv2D_input_shape_set)
    output_shape = property(_conv2d.Conv2D_output_shape_get, _conv2d.Conv2D_output_shape_set)

    def __init__(self):
        _conv2d.Conv2D_swiginit(self, _conv2d.new_Conv2D())
    __swig_destroy__ = _conv2d.delete_Conv2D

# Register Conv2D in _conv2d:
_conv2d.Conv2D_swigregister(Conv2D)


def activate(arg1, arg2, arg3):
    return _conv2d.activate(arg1, arg2, arg3)

def sigmoid(arg1, arg2):
    return _conv2d.sigmoid(arg1, arg2)

def softplus(arg1, arg2):
    return _conv2d.softplus(arg1, arg2)

def softsign(arg1, arg2):
    return _conv2d.softsign(arg1, arg2)

def hard_sigmoid(arg1, arg2):
    return _conv2d.hard_sigmoid(arg1, arg2)

def exp_activation(arg1, arg2):
    return _conv2d.exp_activation(arg1, arg2)

def exponential(arg1):
    return _conv2d.exponential(arg1)

def relu(arg1, arg2):
    return _conv2d.relu(arg1, arg2)

def elu(arg1, arg2, arg3):
    return _conv2d.elu(arg1, arg2, arg3)

def selu(arg1, arg2):
    return _conv2d.selu(arg1, arg2)

def hyper_tan(arg1, arg2):
    return _conv2d.hyper_tan(arg1, arg2)

def softmax(arg1, arg2):
    return _conv2d.softmax(arg1, arg2)
class input(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _conv2d.input_swiginit(self, _conv2d.new_input(nelements))
    __swig_destroy__ = _conv2d.delete_input

    def __getitem__(self, index):
        return _conv2d.input___getitem__(self, index)

    def __setitem__(self, index, value):
        return _conv2d.input___setitem__(self, index, value)

    def cast(self):
        return _conv2d.input_cast(self)

    @staticmethod
    def frompointer(t):
        return _conv2d.input_frompointer(t)

# Register input in _conv2d:
_conv2d.input_swigregister(input)
cvar = _conv2d.cvar
conv1d_1_W = cvar.conv1d_1_W
conv1d_1_b = cvar.conv1d_1_b
conv1d_2_W = cvar.conv1d_2_W
conv1d_2_b = cvar.conv1d_2_b
dense_1_W = cvar.dense_1_W
dense_1_b = cvar.dense_1_b
dense_2_W = cvar.dense_2_W
dense_2_b = cvar.dense_2_b
dense_3_W = cvar.dense_3_W
dense_3_b = cvar.dense_3_b
dense_4_W = cvar.dense_4_W
dense_4_b = cvar.dense_4_b
dense_5_W = cvar.dense_5_W
dense_5_b = cvar.dense_5_b
dense_6_W = cvar.dense_6_W
dense_6_b = cvar.dense_6_b
dense_7_W = cvar.dense_7_W
dense_7_b = cvar.dense_7_b
dense_8_W = cvar.dense_8_W
dense_8_b = cvar.dense_8_b

def input_frompointer(t):
    return _conv2d.input_frompointer(t)



